version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - docker/install-docker-compose
      - run:
          name: Ejecutar tests con Docker Compose
          command: |
            docker-compose -f docker-compose.test.yml up --build --force-recreate test --exit-code-from test
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test