version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.11.0
        environment:
          MONGO_DB_URL: mongodb://localhost:27017/adoptme_test
          COVERALLS_REPO_TOKEN: AznMYbzBxdcxcfBMg8x9oVfoN9ZRNV3Ox
      - image: cimg/mongo:7.0
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: COVERALLS_REPO_TOKEN=AznMYbzBxdcxcfBMg8x9oVfoN9ZRNV3Ox npm run test:cov
          name: Run tests
      - coveralls/upload:
          parallel: true
          flag_name: Test 1
          verbose: true

workflows:
  build_test_deploy:
    jobs:
      - build_and_test