version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0

jobs:
  build_and_test:
    machine:
      image: ubuntu-2204:2023.07.1
    steps:
      - checkout
      - docker/install-docker-compose
      - run:
          name: Ejecutar tests con Docker Compose
          command: |
            docker-compose -f docker-compose.test.yml up --build --exit-code-from test
      - run:
          name: Compilar aplicación
          command: docker-compose -f docker-compose.test.yml run --rm test npm run build
      - persist_to_workspace:
          root: ~/project
          paths: .
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test